#!/usr/bin/env bash
#
# .bash_profile for login

# load the shell dotfiles
for file in ${HOME}/dotfiles/shell/{path,exports,aliases,functions,extra}; do
    [[ (-r "${file}") && (-f "${file}") ]] && source "${file}"
done
unset file
# load bash specific dotfiles
for file in ${HOME}/dotfiles/shell/bash/{bash_prompt,bash_options,bash_extra,tmuxinator_completions}; do
    [[ (-r "${file}") && (-f "${file}") ]] && source "${file}"
done
unset file

# Add tab completion for many Bash commands
if which brew &> /dev/null && [[ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]]; then
    source "$(brew --prefix)/share/bash-completion/bash_completion"
elif [[ -f /etc/bash_completion ]]; then
    source /etc/bash_completion
fi

# Enable tab completion for `g` by marking it as an alias for `git`
if type _git &> /dev/null && [[ -f /usr/local/etc/bash_completion.d/git-completion.bash ]]; then
    complete -o default -o nospace -F _git g;
fi;

[[ -f "${NVM_DIR}/bash_completion" ]] \
    && source "${NVM_DIR}/bash_completion"
