#!/usr/bin/env bash
#
# bash options

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Include filenames beginning with a "." in the filename expansion
shopt -s dotglob

# Use extended pattern matching features
shopt -s extglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
    shopt -s "${option}" 2> /dev/null
done
