#!/usr/bin/env zsh
#
# .zshrc

# Location of prezto and zsh dotfiles
export ZDOTDIR="${HOME}/dotfiles/shell/zsh"

# load prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# load the shell dotfiles
for file in ${HOME}/dotfiles/shell/{path,exports,aliases,functions,extra}; do
    [[ (-r "${file}") && (-f "${file}") ]] && source "${file}"
done
unset file
# load zsh specifc dotfiles
for file in ${HOME}/dotfiles/shell/zsh/{zshextra,tmuxinator_completions}; do
    [[ (-r "${file}") && (-f "${file}") ]] && source "${file}"
done
unset file

